### ISSUE TITLE
Caching for github actions

### ISSUE THREAD

**Issue by stefsmeets** [dianna-ai/dianna#475]
I just noticed that your tests are taking a very long time to run. They can be much, much faster if you cache the pip install step.

Can be done by adding this step to the actions:

```yaml
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}
```
