### ISSUE TITLE
Fix github actions running when PR is in draft state

### ISSUE THREAD

**Issue by stefsmeets** [dianna-ai/dianna#519]
In #482 I intended to make a change so that the tests only run when the PR is marked as ready for review.  This saves CI use which in turn reduces the footprint of DIANNA 🌱

This does not happen at the moment, because I forgot to add the following line to the github actions:

```
jobs:
  build:
    name: ...
    if: github.event.pull_request.draft == false
    ...
```
